apiVersion: apps/v1
kind: Deployment
metadata:
  name: tertiarycare-api
  labels:
    app.kubernetes.io/name: tertiarycare-deploy
    app.kubernetes.io/component: tertiarycare-deploy
spec:
  replicas: 3 
  selector:
    matchLabels:
      app.kubernetes.io/name: tertiarycare-deploy
      app.kubernetes.io/component: tertiarycare-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tertiarycare-deploy
        app.kubernetes.io/component: tertiarycare-deploy
    spec:
      containers:
        - name: tertiarycare-api
          image: khuloodawad/tertiarycare:latest  # Docker Hub repository name
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000  
