apiVersion: v1
kind: Service
metadata:
  name: tertiarycare-api
spec:
  selector:
    app.kubernetes.io/component: tertiarycare-deploy
    app.kubernetes.io/name: tertiarycare-deploy
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000  